thread 'main' panicked at 'Unsupported file extension: Some("py")', bin/kecc.rs:123:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
